# Site settings
title: Alireza Miraliakbar
email: alireza.miraliakbar@uconn.edu
description: Personal academic website
baseurl: ""
url: "https://alirezamiraliakbar.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Author information
author:
  name: Alireza Miraliakbar
  email: alireza.miraliakbar@uconn.edu

# Social links (uncomment and update as needed)
github_username: AlirezaMiraliakbar
linkedin_username: alirezamiraliakbar